Creating Project Module
mokot/reportko-api pull request #3
Opened 2021-07-13 09:01 UTC by mokot

Creating Project Module and endpoints:
get all projects, get project by id or name, create project, update
project by id or name, delete project by id or name.

2021-07-13 09:35 UTC, norikkozmelj requested changes

2021-07-13 09:35 UTC, norikkozmelj commented on src/model/dto/project.create.dto.ts
> +  team: TeamKey;
It is better to use team_id than team key. Try avoiding using keys.

2021-07-13 09:35 UTC, norikkozmelj commented on src/model/dto/project.update.dto.ts
> +  team: TeamKey;
Same as on Post DTO

2021-07-13 09:35 UTC, norikkozmelj commented on src/entity/project.entity.ts
> +  @Exclude()
You can remove this, as you renamed team to team_id in line 41.

2021-07-13 09:35 UTC, norikkozmelj commented on src/entity/project.entity.ts
> +  @Column({ type: 'varchar', nullable: false, unique: true })
nullable: false is by default, only use this attribute when you set it to true

2021-07-13 09:35 UTC, norikkozmelj commented on src/entity/project.entity.ts
> +  @Transform((team) => team.value.key)
Remove transform as we will use whole object on frontend.

2021-07-13 09:35 UTC, norikkozmelj commented on src/entity/project.entity.ts
> +  @Column({ type: 'boolean', nullable: true, default: true })
This cannot be nullable.

2021-07-13 09:35 UTC, norikkozmelj commented on src/model/dto/project.create.dto.ts
> +  @IsOptional()
this is mandatory, not optional.

2021-07-13 09:35 UTC, norikkozmelj commented on src/model/dto/project.update.dto.ts
> +  name: string;
if a field is optional then use ? when declaring a field.
Example:
name?: string;

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.controller.ts
> +    const project = await this.projectService.getOneById(id);
move this to service and send id in the function. All querying of the database should be done in service, not in controller.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.controller.ts
> +  // .../project/name/name
Not needed.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.controller.ts
> +    const project = await this.projectService.getOneById(id);
Same as with update.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.controller.ts
> +  @ApiBearerAuth()
Same here.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.controller.ts
> +  @ApiBearerAuth()
Not needed

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    projectCredentials.name = projectCredentials.name.toLowerCase();
this can be done in entity with transform.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +      .getTeamByTeamKey(projectCredentials.team);
here you will use team id instead of key.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    console.log("tu");
I am here :)

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    const existingTeam = await this.getProjectByName(projectCredentials.name);
existingProject

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    project: Project,
here will be id

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +      projectTeam = await this.teamService.getTeamByTeamKey(
query by id and use let not var

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    // New team
remove this

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +          name: existingProject ? project.name : projectCredentials.name
Move this before query and then use just .update(project) without set.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    if (!updateProject) {
Not needed.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +  async deleteProject(project: Project): Promise<DeleteResult> {
Here you will have id. First query for that project and if there is no project with that id throw error.

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    .getOne();
not neded

2021-07-13 09:35 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +}
not needed

2021-07-14 11:15 UTC, mokot commented on src/module/project/project.service.ts
> +    .getOne();
leave this in service

2021-07-14 12:16 UTC, mokot reviewed
I have resolved problems

2021-07-14 12:41 UTC, norikkozmelj requested changes

2021-07-14 12:41 UTC, norikkozmelj commented on src/entity/project.entity.ts
> +  }
Well done!

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    projectCredentials.name = projectCredentials.name.toLowerCase();
This has to be removed as you covered this in the entity.

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    project.team = projectTeam;
What if the team with that id does not exist?

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    const project = await this.getOneById(id);
What if there is no project with that id?

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +      projectTeam = await this.teamService.getTeamByTeamId(
What if there is no team with that id?

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +    project.name = existingProject ? project.name : projectCredentials.name;
you have to check if there is the name in the credentials not if the project already exists.

2021-07-14 12:41 UTC, norikkozmelj commented on src/module/project/project.service.ts
> +  }
If you cover all the possibilites, you do not need this check. Just return result of the await.

2021-07-14 13:47 UTC, mokot commented on src/module/project/project.service.ts
> +    const project = await this.getOneById(id);
Same result as in getTeamBuTeamId (invalid_project_id)

2021-07-14 13:52 UTC, mokot commented on src/module/project/project.service.ts
> +    project.name = existingProject ? project.name : projectCredentials.name;
If there is name in project credentials and if that name is not equal to current name, then i check if there is project with that name in database. If project exists i throw conflict exception (invalid_project_name). If value of existing project is false/null/undefined i replace the name with project credentials name, else i keep the same name.

2021-07-14 14:05 UTC, mokot commented on src/module/project/project.service.ts
> +    project.name = existingProject ? project.name : projectCredentials.name;
Mb, if name is not in the credentials, function does not work ... I will fix the problem

2021-07-15 12:07 UTC, jakapurg commented on src/entity/project.entity.ts
> +  @IsString()
No need for class validators in entity files. (Already handled in DTO's)

2021-07-15 12:07 UTC, jakapurg commented on src/entity/project.entity.ts
> +  @IsBoolean()
Same as above

2021-07-15 12:08 UTC, jakapurg commented on src/model/dto/project.create.dto.ts
> +  team_id: number;
You can add decorator for positive integer here

2021-07-15 12:08 UTC, jakapurg commented on src/model/dto/project.update.dto.ts
> +  team_id?: number;
Decorator for positive integer

2021-07-15 12:11 UTC, jakapurg commented on src/module/project/project.controller.ts
> +    return this.projectService.getOneById(Number(id));
Is Number() needed ?

2021-07-15 12:15 UTC, jakapurg commented on src/module/project/project.service.ts
> +  }
Merge functions together. Hint: Use FindOneOptions

2021-07-15 12:15 UTC, jakapurg commented on src/module/project/project.service.ts
> +  }
Use FindManyOptions, for future queries

2021-07-15 12:54 UTC, mokot reviewed
Problems resolved.
I have not yet merged functions

2021-07-16 06:48 UTC, mokot reviewed
Comments Resolved

2021-07-16 08:14 UTC, jakapurg commented on src/module/project/project.service.ts
> +  }
Use FindManyOptions

2021-07-16 08:17 UTC, jakapurg commented on src/module/project/project.controller.ts
> +    );
NB: {id:id} is the same as {id}

2021-07-16 08:18 UTC, jakapurg commented on src/module/project/project.service.ts
> +      }
NB: {id:id} is the same as {id}

2021-07-16 09:05 UTC, mokot commented on src/module/project/project.service.ts
> +    return getRepository(Project).find(options);
await

2021-07-16 09:10 UTC, jakapurg approved these changes

2021-07-16 09:26 UTC, jakapurg approved these changes

2021-07-16 12:47 UTC, merged